// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: proto/idservice.proto

package idservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchRequest) Reset() {
	*x = GetBatchRequest{}
	mi := &file_proto_idservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchRequest) ProtoMessage() {}

func (x *GetBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchRequest.ProtoReflect.Descriptor instead.
func (*GetBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_idservice_proto_rawDescGZIP(), []int{0}
}

type GetBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchResponse) Reset() {
	*x = GetBatchResponse{}
	mi := &file_proto_idservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchResponse) ProtoMessage() {}

func (x *GetBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_idservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchResponse.ProtoReflect.Descriptor instead.
func (*GetBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_idservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetBatchResponse) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_proto_idservice_proto protoreflect.FileDescriptor

const file_proto_idservice_proto_rawDesc = "" +
	"\n" +
	"\x15proto/idservice.proto\x12\tgenerator\"\x11\n" +
	"\x0fGetBatchRequest\"$\n" +
	"\x10GetBatchResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids2R\n" +
	"\tIDService\x12E\n" +
	"\n" +
	"GetIDBatch\x12\x1a.generator.GetBatchRequest\x1a\x1b.generator.GetBatchResponseB\x13Z\x11./proto/idserviceb\x06proto3"

var (
	file_proto_idservice_proto_rawDescOnce sync.Once
	file_proto_idservice_proto_rawDescData []byte
)

func file_proto_idservice_proto_rawDescGZIP() []byte {
	file_proto_idservice_proto_rawDescOnce.Do(func() {
		file_proto_idservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_idservice_proto_rawDesc), len(file_proto_idservice_proto_rawDesc)))
	})
	return file_proto_idservice_proto_rawDescData
}

var file_proto_idservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_idservice_proto_goTypes = []any{
	(*GetBatchRequest)(nil),  // 0: generator.GetBatchRequest
	(*GetBatchResponse)(nil), // 1: generator.GetBatchResponse
}
var file_proto_idservice_proto_depIdxs = []int32{
	0, // 0: generator.IDService.GetIDBatch:input_type -> generator.GetBatchRequest
	1, // 1: generator.IDService.GetIDBatch:output_type -> generator.GetBatchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_idservice_proto_init() }
func file_proto_idservice_proto_init() {
	if File_proto_idservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_idservice_proto_rawDesc), len(file_proto_idservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_idservice_proto_goTypes,
		DependencyIndexes: file_proto_idservice_proto_depIdxs,
		MessageInfos:      file_proto_idservice_proto_msgTypes,
	}.Build()
	File_proto_idservice_proto = out.File
	file_proto_idservice_proto_goTypes = nil
	file_proto_idservice_proto_depIdxs = nil
}
