// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: proto/cacheservice.proto

package cacheservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UrlCacheService_WriteURLPair_FullMethodName = "/dbservices.UrlCacheService/WriteURLPair"
	UrlCacheService_GetLongURL_FullMethodName   = "/dbservices.UrlCacheService/GetLongURL"
	UrlCacheService_GetShortURL_FullMethodName  = "/dbservices.UrlCacheService/GetShortURL"
)

// UrlCacheServiceClient is the client API for UrlCacheService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrlCacheServiceClient interface {
	WriteURLPair(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	GetLongURL(ctx context.Context, in *GetLongURLRequest, opts ...grpc.CallOption) (*GetLongURLResponse, error)
	GetShortURL(ctx context.Context, in *GetShortURLRequest, opts ...grpc.CallOption) (*GetShortURLResponse, error)
}

type urlCacheServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUrlCacheServiceClient(cc grpc.ClientConnInterface) UrlCacheServiceClient {
	return &urlCacheServiceClient{cc}
}

func (c *urlCacheServiceClient) WriteURLPair(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, UrlCacheService_WriteURLPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlCacheServiceClient) GetLongURL(ctx context.Context, in *GetLongURLRequest, opts ...grpc.CallOption) (*GetLongURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLongURLResponse)
	err := c.cc.Invoke(ctx, UrlCacheService_GetLongURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urlCacheServiceClient) GetShortURL(ctx context.Context, in *GetShortURLRequest, opts ...grpc.CallOption) (*GetShortURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShortURLResponse)
	err := c.cc.Invoke(ctx, UrlCacheService_GetShortURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrlCacheServiceServer is the server API for UrlCacheService service.
// All implementations must embed UnimplementedUrlCacheServiceServer
// for forward compatibility.
type UrlCacheServiceServer interface {
	WriteURLPair(context.Context, *CreateRequest) (*CreateResponse, error)
	GetLongURL(context.Context, *GetLongURLRequest) (*GetLongURLResponse, error)
	GetShortURL(context.Context, *GetShortURLRequest) (*GetShortURLResponse, error)
	mustEmbedUnimplementedUrlCacheServiceServer()
}

// UnimplementedUrlCacheServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUrlCacheServiceServer struct{}

func (UnimplementedUrlCacheServiceServer) WriteURLPair(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteURLPair not implemented")
}
func (UnimplementedUrlCacheServiceServer) GetLongURL(context.Context, *GetLongURLRequest) (*GetLongURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLongURL not implemented")
}
func (UnimplementedUrlCacheServiceServer) GetShortURL(context.Context, *GetShortURLRequest) (*GetShortURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShortURL not implemented")
}
func (UnimplementedUrlCacheServiceServer) mustEmbedUnimplementedUrlCacheServiceServer() {}
func (UnimplementedUrlCacheServiceServer) testEmbeddedByValue()                         {}

// UnsafeUrlCacheServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrlCacheServiceServer will
// result in compilation errors.
type UnsafeUrlCacheServiceServer interface {
	mustEmbedUnimplementedUrlCacheServiceServer()
}

func RegisterUrlCacheServiceServer(s grpc.ServiceRegistrar, srv UrlCacheServiceServer) {
	// If the following call panics, it indicates UnimplementedUrlCacheServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UrlCacheService_ServiceDesc, srv)
}

func _UrlCacheService_WriteURLPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlCacheServiceServer).WriteURLPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrlCacheService_WriteURLPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlCacheServiceServer).WriteURLPair(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlCacheService_GetLongURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLongURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlCacheServiceServer).GetLongURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrlCacheService_GetLongURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlCacheServiceServer).GetLongURL(ctx, req.(*GetLongURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrlCacheService_GetShortURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShortURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrlCacheServiceServer).GetShortURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrlCacheService_GetShortURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrlCacheServiceServer).GetShortURL(ctx, req.(*GetShortURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UrlCacheService_ServiceDesc is the grpc.ServiceDesc for UrlCacheService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrlCacheService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbservices.UrlCacheService",
	HandlerType: (*UrlCacheServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteURLPair",
			Handler:    _UrlCacheService_WriteURLPair_Handler,
		},
		{
			MethodName: "GetLongURL",
			Handler:    _UrlCacheService_GetLongURL_Handler,
		},
		{
			MethodName: "GetShortURL",
			Handler:    _UrlCacheService_GetShortURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cacheservice.proto",
}
