// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: proto/cacheservice.proto

package cacheservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      int64                  `protobuf:"varint,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_cacheservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cacheservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_cacheservice_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetShortUrl() int64 {
	if x != nil {
		return x.ShortUrl
	}
	return 0
}

func (x *CreateRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      int64                  `protobuf:"varint,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_cacheservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cacheservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_cacheservice_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetShortUrl() int64 {
	if x != nil {
		return x.ShortUrl
	}
	return 0
}

type GetLongURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      int64                  `protobuf:"varint,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLongURLRequest) Reset() {
	*x = GetLongURLRequest{}
	mi := &file_proto_cacheservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLongURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongURLRequest) ProtoMessage() {}

func (x *GetLongURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cacheservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongURLRequest.ProtoReflect.Descriptor instead.
func (*GetLongURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_cacheservice_proto_rawDescGZIP(), []int{2}
}

func (x *GetLongURLRequest) GetShortUrl() int64 {
	if x != nil {
		return x.ShortUrl
	}
	return 0
}

type GetLongURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLongURLResponse) Reset() {
	*x = GetLongURLResponse{}
	mi := &file_proto_cacheservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLongURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongURLResponse) ProtoMessage() {}

func (x *GetLongURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cacheservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongURLResponse.ProtoReflect.Descriptor instead.
func (*GetLongURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_cacheservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetLongURLResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type GetShortURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      int64                  `protobuf:"varint,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortURLRequest) Reset() {
	*x = GetShortURLRequest{}
	mi := &file_proto_cacheservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortURLRequest) ProtoMessage() {}

func (x *GetShortURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cacheservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortURLRequest.ProtoReflect.Descriptor instead.
func (*GetShortURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_cacheservice_proto_rawDescGZIP(), []int{4}
}

func (x *GetShortURLRequest) GetShortUrl() int64 {
	if x != nil {
		return x.ShortUrl
	}
	return 0
}

func (x *GetShortURLRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type GetShortURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      int64                  `protobuf:"varint,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShortURLResponse) Reset() {
	*x = GetShortURLResponse{}
	mi := &file_proto_cacheservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShortURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShortURLResponse) ProtoMessage() {}

func (x *GetShortURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cacheservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShortURLResponse.ProtoReflect.Descriptor instead.
func (*GetShortURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_cacheservice_proto_rawDescGZIP(), []int{5}
}

func (x *GetShortURLResponse) GetShortUrl() int64 {
	if x != nil {
		return x.ShortUrl
	}
	return 0
}

var File_proto_cacheservice_proto protoreflect.FileDescriptor

const file_proto_cacheservice_proto_rawDesc = "" +
	"\n" +
	"\x18proto/cacheservice.proto\x12\n" +
	"dbservices\"G\n" +
	"\rCreateRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\x03R\bshortUrl\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\"-\n" +
	"\x0eCreateResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\x03R\bshortUrl\"0\n" +
	"\x11GetLongURLRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\x03R\bshortUrl\"/\n" +
	"\x12GetLongURLResponse\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl\"L\n" +
	"\x12GetShortURLRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\x03R\bshortUrl\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\"2\n" +
	"\x13GetShortURLResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\x03R\bshortUrl2\xf5\x01\n" +
	"\x0fUrlCacheService\x12E\n" +
	"\fWriteURLPair\x12\x19.dbservices.CreateRequest\x1a\x1a.dbservices.CreateResponse\x12K\n" +
	"\n" +
	"GetLongURL\x12\x1d.dbservices.GetLongURLRequest\x1a\x1e.dbservices.GetLongURLResponse\x12N\n" +
	"\vGetShortURL\x12\x1e.dbservices.GetShortURLRequest\x1a\x1f.dbservices.GetShortURLResponseB\x16Z\x14./proto/cacheserviceb\x06proto3"

var (
	file_proto_cacheservice_proto_rawDescOnce sync.Once
	file_proto_cacheservice_proto_rawDescData []byte
)

func file_proto_cacheservice_proto_rawDescGZIP() []byte {
	file_proto_cacheservice_proto_rawDescOnce.Do(func() {
		file_proto_cacheservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cacheservice_proto_rawDesc), len(file_proto_cacheservice_proto_rawDesc)))
	})
	return file_proto_cacheservice_proto_rawDescData
}

var file_proto_cacheservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_cacheservice_proto_goTypes = []any{
	(*CreateRequest)(nil),       // 0: dbservices.CreateRequest
	(*CreateResponse)(nil),      // 1: dbservices.CreateResponse
	(*GetLongURLRequest)(nil),   // 2: dbservices.GetLongURLRequest
	(*GetLongURLResponse)(nil),  // 3: dbservices.GetLongURLResponse
	(*GetShortURLRequest)(nil),  // 4: dbservices.GetShortURLRequest
	(*GetShortURLResponse)(nil), // 5: dbservices.GetShortURLResponse
}
var file_proto_cacheservice_proto_depIdxs = []int32{
	0, // 0: dbservices.UrlCacheService.WriteURLPair:input_type -> dbservices.CreateRequest
	2, // 1: dbservices.UrlCacheService.GetLongURL:input_type -> dbservices.GetLongURLRequest
	4, // 2: dbservices.UrlCacheService.GetShortURL:input_type -> dbservices.GetShortURLRequest
	1, // 3: dbservices.UrlCacheService.WriteURLPair:output_type -> dbservices.CreateResponse
	3, // 4: dbservices.UrlCacheService.GetLongURL:output_type -> dbservices.GetLongURLResponse
	5, // 5: dbservices.UrlCacheService.GetShortURL:output_type -> dbservices.GetShortURLResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cacheservice_proto_init() }
func file_proto_cacheservice_proto_init() {
	if File_proto_cacheservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cacheservice_proto_rawDesc), len(file_proto_cacheservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_cacheservice_proto_goTypes,
		DependencyIndexes: file_proto_cacheservice_proto_depIdxs,
		MessageInfos:      file_proto_cacheservice_proto_msgTypes,
	}.Build()
	File_proto_cacheservice_proto = out.File
	file_proto_cacheservice_proto_goTypes = nil
	file_proto_cacheservice_proto_depIdxs = nil
}
