// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: proto/dbservices.proto

package dbservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      int64                  `protobuf:"varint,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	LongUrl       string                 `protobuf:"bytes,2,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_dbservices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbservices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbservices_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetShortUrl() int64 {
	if x != nil {
		return x.ShortUrl
	}
	return 0
}

func (x *CreateRequest) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      int64                  `protobuf:"varint,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_dbservices_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbservices_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbservices_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetShortUrl() int64 {
	if x != nil {
		return x.ShortUrl
	}
	return 0
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      int64                  `protobuf:"varint,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_dbservices_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbservices_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_dbservices_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetShortUrl() int64 {
	if x != nil {
		return x.ShortUrl
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LongUrl       string                 `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_dbservices_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_dbservices_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_dbservices_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

var File_proto_dbservices_proto protoreflect.FileDescriptor

const file_proto_dbservices_proto_rawDesc = "" +
	"\n" +
	"\x16proto/dbservices.proto\x12\n" +
	"dbservices\"G\n" +
	"\rCreateRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\x03R\bshortUrl\x12\x19\n" +
	"\blong_url\x18\x02 \x01(\tR\alongUrl\"-\n" +
	"\x0eCreateResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\x03R\bshortUrl\")\n" +
	"\n" +
	"GetRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\x03R\bshortUrl\"(\n" +
	"\vGetResponse\x12\x19\n" +
	"\blong_url\x18\x01 \x01(\tR\alongUrl2X\n" +
	"\x0fStoreUrlService\x12E\n" +
	"\fWriteURLPair\x12\x19.dbservices.CreateRequest\x1a\x1a.dbservices.CreateResponse2O\n" +
	"\x0eReadUrlService\x12=\n" +
	"\n" +
	"GetLongURL\x12\x16.dbservices.GetRequest\x1a\x17.dbservices.GetResponseB\x13Z\x11./proto/dbserviceb\x06proto3"

var (
	file_proto_dbservices_proto_rawDescOnce sync.Once
	file_proto_dbservices_proto_rawDescData []byte
)

func file_proto_dbservices_proto_rawDescGZIP() []byte {
	file_proto_dbservices_proto_rawDescOnce.Do(func() {
		file_proto_dbservices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_dbservices_proto_rawDesc), len(file_proto_dbservices_proto_rawDesc)))
	})
	return file_proto_dbservices_proto_rawDescData
}

var file_proto_dbservices_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_dbservices_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: dbservices.CreateRequest
	(*CreateResponse)(nil), // 1: dbservices.CreateResponse
	(*GetRequest)(nil),     // 2: dbservices.GetRequest
	(*GetResponse)(nil),    // 3: dbservices.GetResponse
}
var file_proto_dbservices_proto_depIdxs = []int32{
	0, // 0: dbservices.StoreUrlService.WriteURLPair:input_type -> dbservices.CreateRequest
	2, // 1: dbservices.ReadUrlService.GetLongURL:input_type -> dbservices.GetRequest
	1, // 2: dbservices.StoreUrlService.WriteURLPair:output_type -> dbservices.CreateResponse
	3, // 3: dbservices.ReadUrlService.GetLongURL:output_type -> dbservices.GetResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_dbservices_proto_init() }
func file_proto_dbservices_proto_init() {
	if File_proto_dbservices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_dbservices_proto_rawDesc), len(file_proto_dbservices_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_dbservices_proto_goTypes,
		DependencyIndexes: file_proto_dbservices_proto_depIdxs,
		MessageInfos:      file_proto_dbservices_proto_msgTypes,
	}.Build()
	File_proto_dbservices_proto = out.File
	file_proto_dbservices_proto_goTypes = nil
	file_proto_dbservices_proto_depIdxs = nil
}
