// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: proto/dbservices.proto

package dbservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoreUrlService_WriteURLPair_FullMethodName = "/dbservices.StoreUrlService/WriteURLPair"
)

// StoreUrlServiceClient is the client API for StoreUrlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreUrlServiceClient interface {
	WriteURLPair(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type storeUrlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreUrlServiceClient(cc grpc.ClientConnInterface) StoreUrlServiceClient {
	return &storeUrlServiceClient{cc}
}

func (c *storeUrlServiceClient) WriteURLPair(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, StoreUrlService_WriteURLPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreUrlServiceServer is the server API for StoreUrlService service.
// All implementations must embed UnimplementedStoreUrlServiceServer
// for forward compatibility.
type StoreUrlServiceServer interface {
	WriteURLPair(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedStoreUrlServiceServer()
}

// UnimplementedStoreUrlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreUrlServiceServer struct{}

func (UnimplementedStoreUrlServiceServer) WriteURLPair(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteURLPair not implemented")
}
func (UnimplementedStoreUrlServiceServer) mustEmbedUnimplementedStoreUrlServiceServer() {}
func (UnimplementedStoreUrlServiceServer) testEmbeddedByValue()                         {}

// UnsafeStoreUrlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreUrlServiceServer will
// result in compilation errors.
type UnsafeStoreUrlServiceServer interface {
	mustEmbedUnimplementedStoreUrlServiceServer()
}

func RegisterStoreUrlServiceServer(s grpc.ServiceRegistrar, srv StoreUrlServiceServer) {
	// If the following call panics, it indicates UnimplementedStoreUrlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoreUrlService_ServiceDesc, srv)
}

func _StoreUrlService_WriteURLPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreUrlServiceServer).WriteURLPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoreUrlService_WriteURLPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreUrlServiceServer).WriteURLPair(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoreUrlService_ServiceDesc is the grpc.ServiceDesc for StoreUrlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoreUrlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbservices.StoreUrlService",
	HandlerType: (*StoreUrlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WriteURLPair",
			Handler:    _StoreUrlService_WriteURLPair_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dbservices.proto",
}

const (
	ReadUrlService_GetLongURL_FullMethodName = "/dbservices.ReadUrlService/GetLongURL"
)

// ReadUrlServiceClient is the client API for ReadUrlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReadUrlServiceClient interface {
	GetLongURL(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type readUrlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReadUrlServiceClient(cc grpc.ClientConnInterface) ReadUrlServiceClient {
	return &readUrlServiceClient{cc}
}

func (c *readUrlServiceClient) GetLongURL(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, ReadUrlService_GetLongURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReadUrlServiceServer is the server API for ReadUrlService service.
// All implementations must embed UnimplementedReadUrlServiceServer
// for forward compatibility.
type ReadUrlServiceServer interface {
	GetLongURL(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedReadUrlServiceServer()
}

// UnimplementedReadUrlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReadUrlServiceServer struct{}

func (UnimplementedReadUrlServiceServer) GetLongURL(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLongURL not implemented")
}
func (UnimplementedReadUrlServiceServer) mustEmbedUnimplementedReadUrlServiceServer() {}
func (UnimplementedReadUrlServiceServer) testEmbeddedByValue()                        {}

// UnsafeReadUrlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReadUrlServiceServer will
// result in compilation errors.
type UnsafeReadUrlServiceServer interface {
	mustEmbedUnimplementedReadUrlServiceServer()
}

func RegisterReadUrlServiceServer(s grpc.ServiceRegistrar, srv ReadUrlServiceServer) {
	// If the following call panics, it indicates UnimplementedReadUrlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReadUrlService_ServiceDesc, srv)
}

func _ReadUrlService_GetLongURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReadUrlServiceServer).GetLongURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReadUrlService_GetLongURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReadUrlServiceServer).GetLongURL(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReadUrlService_ServiceDesc is the grpc.ServiceDesc for ReadUrlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReadUrlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dbservices.ReadUrlService",
	HandlerType: (*ReadUrlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLongURL",
			Handler:    _ReadUrlService_GetLongURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/dbservices.proto",
}
