// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: internal/proto/idservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDRequest) Reset() {
	*x = IDRequest{}
	mi := &file_internal_proto_idservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDRequest) ProtoMessage() {}

func (x *IDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_idservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDRequest.ProtoReflect.Descriptor instead.
func (*IDRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_idservice_proto_rawDescGZIP(), []int{0}
}

type IDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IDResponse) Reset() {
	*x = IDResponse{}
	mi := &file_internal_proto_idservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDResponse) ProtoMessage() {}

func (x *IDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_idservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDResponse.ProtoReflect.Descriptor instead.
func (*IDResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_idservice_proto_rawDescGZIP(), []int{1}
}

func (x *IDResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IDResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_internal_proto_idservice_proto protoreflect.FileDescriptor

const file_internal_proto_idservice_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/idservice.proto\x12\tgenerator\"\v\n" +
	"\tIDRequest\"0\n" +
	"\n" +
	"IDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code2E\n" +
	"\tIDService\x128\n" +
	"\tGetNextID\x12\x14.generator.IDRequest\x1a\x15.generator.IDResponseB\tZ\a./protob\x06proto3"

var (
	file_internal_proto_idservice_proto_rawDescOnce sync.Once
	file_internal_proto_idservice_proto_rawDescData []byte
)

func file_internal_proto_idservice_proto_rawDescGZIP() []byte {
	file_internal_proto_idservice_proto_rawDescOnce.Do(func() {
		file_internal_proto_idservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_idservice_proto_rawDesc), len(file_internal_proto_idservice_proto_rawDesc)))
	})
	return file_internal_proto_idservice_proto_rawDescData
}

var file_internal_proto_idservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_idservice_proto_goTypes = []any{
	(*IDRequest)(nil),  // 0: generator.IDRequest
	(*IDResponse)(nil), // 1: generator.IDResponse
}
var file_internal_proto_idservice_proto_depIdxs = []int32{
	0, // 0: generator.IDService.GetNextID:input_type -> generator.IDRequest
	1, // 1: generator.IDService.GetNextID:output_type -> generator.IDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_idservice_proto_init() }
func file_internal_proto_idservice_proto_init() {
	if File_internal_proto_idservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_idservice_proto_rawDesc), len(file_internal_proto_idservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_idservice_proto_goTypes,
		DependencyIndexes: file_internal_proto_idservice_proto_depIdxs,
		MessageInfos:      file_internal_proto_idservice_proto_msgTypes,
	}.Build()
	File_internal_proto_idservice_proto = out.File
	file_internal_proto_idservice_proto_goTypes = nil
	file_internal_proto_idservice_proto_depIdxs = nil
}
